## DTD Configuration.
event:
  short: "dtd2016"
  full: "Drupal Training Day 2016"
  url: "http://drupaltrainingday.nl/"
  date: "19/02/2016"

auth:
  user: dtd
  password: dtd

local:
  nl:
    country: nl
    lang: nl
    lang_ex: NL_nl
    keyboard: US_int
    time: Europe/Amsterdam
  be:
    country: be
    lang: nl
    lang_ex: NL_nl
    keyboard: FR_az
    time: Europe/Brussels
  en:
    country: uk
    lang: en
    lang_ex: EN_en
    keyboard: US_int
    time: UTC

disk:
  master:
    device: "/dev/sdb"
    mount: "/mnt/master"
  clones: "sdb sdc sdd sde sdf sdg sdh sdi"
