## DTD Sources
sources: "desktop server composer drush"
desktop:
  method: "torrent"
  url: "http://torrent.ubuntu.com/lubuntu/releases/trusty/release/desktop/lubuntu-14.04.2-desktop-i386.iso.torrent"
  file: "lubuntu-14.04.2-desktop-i386.iso"
  size: 737148928
  md5: "aab1b7817c7994e2f9a6fc5f90c609bd"
server:
  method: "torrent"
  url: "http://releases.ubuntu.com/14.04.2/ubuntu-14.04.2-server-i386.iso.torrent"
  file: "ubuntu-14.04.2-server-i386.iso"
  size: 606076928
  md5: "6478187442f331631b65f886cdd229ce"
composer:
  method: "http"
  url: "https://getcomposer.org/composer.phar"
  file: "composer.phar"
drush:
  method: "git"
  url: "https://github.com/drush-ops/drush.git"
  branch: "master"
  dir: "drush"

win_sources: "win_controller win_mysql win_apache win_php win_phpmyadmin"
win_controller:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_controller_1_3_1.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1433089553&use_mirror=garr"
  file: "ZeroXI_controller_1_3_1.exe"
  md5: "53513fefa96cf1b80cf3970e394f85d3"
win_mysql:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_mysql_5_6_26.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1439021890&use_mirror=cznic"
  file: "ZeroXI_mysql_5_6_26.exe"
  md5: "cab10a053d82f61f21f7e178df8fe927"
win_apache:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_apache_2_4_16_p.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1439024365&use_mirror=heanet"
  file: "ZeroXI_apache_2_4_16_p.exe"
  md5: "a1ee79b84348a8368042175b21218c0f"
win_php:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_php_5_5_27_p.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1439024430&use_mirror=heanet"
  file: "ZeroXI_php_5_5_27_p.exe"
  md5: "3a01122e4210e9eff44fa8cbbbdcb215"
win_php:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_phpmyadmin_4_4_12.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1439030627&use_mirror=cznic"
  file: "ZeroXI_phpmyadmin_4_4_12.exe"
  md5: "7881aae84e2eedc45771df8bc9038fc9"

## DTD Tracks
tracks: "main"
main:
  method: "git"
  url: "https://github.com/dtd-tech/dtd-main.git"
  branch: "master"
  dir: "dtd-main"
  drupal: "7.x"
  make: "dtd-main.make"
  authors:
    name: "Drupal Training Day 2015 Team"

intro:
  method: "git"
  url: "https://github.com/dtd-tech/dtd-intro.git"


beginner:

advanced:
  method: "git"


theming:
