## DTD Sources
sources: "desktop server composer drush"
desktop:
  method: "torrent"
  url: "http://cdimage.ubuntu.com/lubuntu/releases/14.04.3/release/lubuntu-14.04.3-desktop-i386.iso.torrent"
  file: "lubuntu-14.04.3-desktop-i386.iso"
  size: 750780416
  md5: "1152f2b9eb1342e8c47421e58a6fda6a"
composer:
  method: "http"
  url: "https://getcomposer.org/composer.phar"
  file: "composer.phar"
drush:
  method: "http"
  url: "https://github.com/drush-ops/drush/releases/download/8.0.1/drush.phar"
  file: "drush.phar"

win_sources: "win_controller win_mysql win_apache win_php win_phpmyadmin"
win_controller:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_controller_1_3_1.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1433089553&use_mirror=garr"
  file: "ZeroXI_controller_1_3_1.exe"
  md5: "53513fefa96cf1b80cf3970e394f85d3"
win_mysql:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_mysql_5_5_46.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1443954071&use_mirror=netcologne"
  file: "ZeroXI_mysql_5_5_46.exe"
  md5: "5ac8091b5a23e4bfabc4630e042176d1"
win_apache:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_apache_2_4_16_p.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1439024365&use_mirror=heanet"
  file: "ZeroXI_apache_2_4_16_p.exe"
  md5: "a1ee79b84348a8368042175b21218c0f"
win_php:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_php_5_5_30_p.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1443954161&use_mirror=netix"
  file: "ZeroXI_php_5_5_30_p.exe"
  md5: "54664350cead26af8b5d412e2f968763"
win_phpmyadmin:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_phpmyadmin_4_4_15.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1443954284&use_mirror=netix"
  file: "ZeroXI_phpmyadmin_4_4_15.exe"
  md5: "fc442ac3b63e5567a5c84622ec7772a7"

## DTD Tracks
tracks: "main"
main:
  method: "git"
  url: "https://github.com/dtd-tech/dtd-main.git"
  dir: "dtd-main"
  branch: "master"
  host: "main.dtd"
  sql: "main.sql"
  drush_alias: "dtd-main.alias.drushrc.php"
  name: "Drupal Training Day 2015"
  description: "Standaard landings pagina met eerste aanwijzingen en tips voor een snelle start met deze Drupal trainings omgeving."
  authors:
    dtd-tech:
      name: "Drupal Training Day 2015 Team"
      url: "http://www.drupaltrainingday.nl"
intro:
  method: "manual"
  dir: "intro"
