## DTD Sources
sources: "desktop server"
desktop:
  method: "torrent"
  url: "http://torrent.ubuntu.com/xubuntu/releases/trusty/release/desktop/lubuntu-14.04.2-desktop-i386.iso.torrent"
  file: "lubuntu-14.04.2-desktop-i386.iso"
  size: 737148928
  md5: "aab1b7817c7994e2f9a6fc5f90c609bd"
server:
  method: "torrent"
  url:"http://releases.ubuntu.com/14.04.2/ubuntu-14.04.2-server-i386.iso.torrent"
  file: "ubuntu-14.04.2-server-i386.iso"
  size: 606076928
  md5: "6478187442f331631b65f886cdd229ce"
