## DTD Sources
sources: "desktop composer drush materials"
desktop:
  method: "torrent"
  url: "http://cdimage.ubuntu.com/lubuntu/releases/14.04.3/release/lubuntu-14.04.3-desktop-i386.iso.torrent"
  file: "lubuntu-14.04.3-desktop-i386.iso"
  size: 750780416
  md5: "1152f2b9eb1342e8c47421e58a6fda6a"
composer:
  method: "http"
  url: "https://getcomposer.org/composer.phar"
  file: "composer.phar"
drush:
  method: "http"
  url: "https://github.com/drush-ops/drush/releases/download/8.0.3/drush.phar"
  file: "drush.phar"

win_sources: "win_controller win_mysql win_apache win_php win_phpmyadmin"
win_controller:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_controller_1_3_1.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1433089553&use_mirror=garr"
  file: "ZeroXI_controller_1_3_1.exe"
  md5: "53513fefa96cf1b80cf3970e394f85d3"
win_mysql:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_mysql_5_5_46.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1443954071&use_mirror=netcologne"
  file: "ZeroXI_mysql_5_5_46.exe"
  md5: "5ac8091b5a23e4bfabc4630e042176d1"
win_apache:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_apache_2_4_16_p.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1439024365&use_mirror=heanet"
  file: "ZeroXI_apache_2_4_16_p.exe"
  md5: "a1ee79b84348a8368042175b21218c0f"
win_php:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_php_5_5_30_p.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1443954161&use_mirror=netix"
  file: "ZeroXI_php_5_5_30_p.exe"
  md5: "54664350cead26af8b5d412e2f968763"
win_phpmyadmin:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_phpmyadmin_4_4_15.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1443954284&use_mirror=netix"
  file: "ZeroXI_phpmyadmin_4_4_15.exe"
  md5: "fc442ac3b63e5567a5c84622ec7772a7"
win_chromium:
  method: "http"
  url: "http://downloads.sourceforge.net/project/crportable/ChromiumPortable_50.0.2633.3.paf.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fcrportable%2Ffiles%2F%3Fsource%3Dnavbar&ts=1454445167&use_mirror=netix"
  file: "ChromiumPortable_50.0.2633.3.paf.exe"

# Tools
win_tools: "win_vbox win_atom win_filezilla win_pdf win_7zip"
win_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0.12-104815-Win.exe"
  file: "VirtualBox-5.0.12-104815-Win.exe"
  size:
win_atom:
  method: "http"
  url: "https://github.com/atom/atom/releases/download/v1.3.2/AtomSetup.exe"
  file: "AtomSetup.exe"
win_filezilla:
  method: "http"
  url: "http://downloads.sourceforge.net/project/filezilla/FileZilla_Client/3.14.1/FileZilla_3.14.1_win64-setup.exe?r=&ts=1451836575&use_mirror=netixx"
  file: "FileZilla_3.14.1_win64-setup.exe"
win_pdf:
  method: "http"
  url: "https://kjkpub.s3.amazonaws.com/sumatrapdf/rel/SumatraPDF-3.1.1.zip"
  file: "SumatraPDF-3.1.1.zip"
win_7zip:
  method: "http"
  url: "http://www.7-zip.org/a/7z1514.exe"
  file: "7z1514.exe"


mac_tools: "mac_vbox mac_atom mac_filezilla"
mac_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0.12-104815-OSX.dmg"
  file: "VirtualBox-5.0.12-104815-OSX.dmg"
mac_atom:
  method: "http"
  url: "https://github.com/atom/atom/releases/download/v1.3.2/atom-mac.zip"
  file: "atom-mac.zip"
mac_filezilla:
  method: "http"
  url: "http://downloads.sourceforge.net/project/filezilla/FileZilla_Client/3.15.0.2/FileZilla_3.15.0.2_macosx-x86.app.tar.bz2?r=&ts=1455656717&use_mirror=heanet"
  file: "FileZilla_3.15.0.2_macosx-x86.app.tar.bz2"

lin_tools: "lin32_vbox lin64_vbox ub32lts_vbox ub64lts_vbox ub32_vbox ub64_vbox os32_vbox os64_vbox"
lin32_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0.12-104815-Linux_x86.run"
  file: "VirtualBox-5.0.12-104815-Linux_x86.run"
lin64_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0.12-104815-Linux_amd64.run"
  file: "VirtualBox-5.0.12-104815-Linux_amd64.run"
ub32lts_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/virtualbox-5.0_5.0.12-104815~Ubuntu~trusty_i386.deb"
  file: "virtualbox-5.0_5.0.12-104815~Ubuntu~trusty_i386.deb"
ub64lts_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/virtualbox-5.0_5.0.12-104815~Ubuntu~trusty_amd64.deb"
  file: "virtualbox-5.0_5.0.12-104815~Ubuntu~trusty_amd64.deb"
ub32_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/virtualbox-5.0_5.0.12-104815~Ubuntu~wily_i386.deb"
  file: "virtualbox-5.0_5.0.12-104815~Ubuntu~wily_i386.deb"
ub64_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/virtualbox-5.0_5.0.12-104815~Ubuntu~wily_amd64.deb"
  file: "virtualbox-5.0_5.0.12-104815~Ubuntu~wily_amd64.deb"
os32_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0-5.0.12_104815_openSUSE132-1.i586.rpm"
  file: "VirtualBox-5.0-5.0.12_104815_openSUSE132-1.i586.rpm"
os64_vbox:
  method: "http"
  url: "http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0-5.0.12_104815_openSUSE132-1.x86_64.rpm"
  file: "VirtualBox-5.0-5.0.12_104815_openSUSE132-1.x86_64.rpm"

## Workshop material sources
workshops: "main wizzlern"
main:
  method: "git"
  url: "https://github.com/dtd-tech/dtd-main.git"
  dir: "dtd-main"
  branch: "master"
wizzlern:
  method: "git"
  url: "https://github.com/dtd-tech/drupaltrainingday.git"
  dir: "drupaltrainingday"
  branch: "dtd2016"
