## DTD Sources
sources: "desktop server composer drush"
desktop:
  method: "torrent"
  url: "http://torrent.ubuntu.com/lubuntu/releases/trusty/release/desktop/lubuntu-14.04.2-desktop-i386.iso.torrent"
  file: "lubuntu-14.04.2-desktop-i386.iso"
  size: 737148928
  md5: "aab1b7817c7994e2f9a6fc5f90c609bd"
server:
  method: "torrent"
  url: "http://releases.ubuntu.com/14.04.2/ubuntu-14.04.2-server-i386.iso.torrent"
  file: "ubuntu-14.04.2-server-i386.iso"
  size: 606076928
  md5: "6478187442f331631b65f886cdd229ce"
composer:
  method: "http"
  url: "https://getcomposer.org/composer.phar"
  file: "composer.phar"
drush:
  method: "git"
  url: "https://github.com/drush-ops/drush.git"
  tag: "7.0.0-alpha9"
  dir: "drush"
uni_controller:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_controller_1_3_1.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1433089553&use_mirror=garr"
  file: "ZeroXI_controller_1_3_1.exe"
  md5: ""
uni_mysql:
  method: "http"
  url: "http://downloads.sourceforge.net/project/miniserver/Uniform%20Server%20ZeroXI/ZeroXImodules/ZeroXI_mysql_5_6_25.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fminiserver%2Ffiles%2FUniform%2520Server%2520ZeroXI%2FZeroXImodules%2F&ts=1433089929&use_mirror=softlayer-ams"
  file: "ZeroXI_mysql_5_6_25.exe"
  md5:
uni_apache:
  method: "http"
  url:
  file:
  md5:
uni_php:
  method: "http"
  url:
  file:
  md5:

## DTD Tracks
tracks: "main"
main:
  method: "git"
  url: "https://github.com/dtd-tech/dtd-main.git"
  branch: "master"
  dir: "dtd-main"
  drupal: "7.x"
  make: "dtd-main.make"
  authors:
    name: "Drupal Training Day 2015 Team"

intro:
  method: "git"
  url: "https://github.com/dtd-tech/dtd-intro.git"


beginner:

advanced:
  method: "git"


theming:
